# Generated by Django 5.2.8 on 2025-11-10 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="related_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mirror_transactions",
                to="banking.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("deposit", "Пополнение"),
                    ("withdrawal", "Снятие"),
                    ("transfer_out", "Перевод (списание)"),
                    ("transfer_in", "Перевод (зачисление)"),
                ],
                max_length=20,
            ),
        ),
    ]
