# Generated by Django 5.2.8 on 2025-11-10 14:12

from django.db import migrations

SUSPECT_CHARS = {
    "Ð",
    "Ñ",
    "Ò",
    "Ó",
    "Â",
    "Ã",
    "Þ",
    "Ý",
    "Ø",
    "µ",
    "¶",
    "·",
    "¸",
    "¹",
    "º",
    "»",
    "¼",
    "½",
    "¾",
    "¿",
    "Ј",
}


def normalize_text(value):
    if not isinstance(value, str) or not value:
        return value
    if not any(char in value for char in SUSPECT_CHARS):
        return value
    for encoding in ("cp1251", "latin1"):
        try:
            decoded = value.encode(encoding).decode("utf-8")
        except UnicodeError:
            continue
        if not any(char in decoded for char in SUSPECT_CHARS):
            return decoded
    return value


def forwards(apps, schema_editor):
    Transaction = apps.get_model("banking", "Transaction")
    for tx in Transaction.objects.exclude(note__isnull=True).exclude(note=""):
        cleaned = normalize_text(tx.note)
        if cleaned != tx.note:
            Transaction.objects.filter(pk=tx.pk).update(note=cleaned)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0002_transaction_related_transaction_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
